import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import Nav from "@/components/Navbar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider className="min-h-screen flex ">
          <div className="w-60 border-r">side bar</div>
          <div className="flex-1">
            <Nav />
            {children}
          </div>
        </NextUIProvider>
      </body>
    </html>
  );
}
